
/*RECODE RACE AND SEX*/
DATA R2_RACECHECK;
SET R2 

(KEEP= RECORD_ID SDEM_SEX sdem_gender SDEM_LANG_MIA_2  DEM_RACE_HISP  DEM_RACE DEM_RACE_OT RAND_ARM
sdem_int_evr
sdem_visit_c
REDCAP_DATA_ACCESS_GROUP 
DEM_RACE_HISP
SDEM_SEX
SDEM_ELIG
EC_PC_YES 
EC_ALL_2 RAND_ELE RAND_ARM
)

;

/*IF     SDEM_LANG_MIA_2 NOT IN (0,1,2,3,4,5) OR */
/*       DEM_RACE_HISP NOT IN (1,2) OR */
/*	   DEM_RACE NOT IN (0,1,2,3,4,5)*/


/*;*/
/*IF RAND_ARM NE .*/
/*;*/

/*ADD RECODE RACE*/
IF DEM_RACE = . THEN R_RACE=SDEM_LANG_MIA_2;
   ELSE IF DEM_RACE = 6 THEN R_RACE=SDEM_LANG_MIA_2;
   ELSE R_RACE = DEM_RACE;

/*ADD RECODE SEX*/
IF SDEM_SEX = . THEN SDEM_SEX=sdem_gender;

	format R_race dem_race_.;
RUN;





/**********************************************FOR ALL-PRESCREENED*/
TITLE "FOR ALL PRESCREEEND PTS";
PROC FREQ DATA=R2_RACECHECK;
TABLES REDCAP_DATA_ACCESS_GROUP*(sdem_elig sdem_int_evr sdem_visit_c);
RUN;

PROC TABULATE DATA=R2_RACECHECK  MISSING;
BY REDCAP_DATA_ACCESS_GROUP;
CLASS REDCAP_DATA_ACCESS_GROUP 
      DEM_RACE_HISP
	  R_race
	  SDEM_SEX
	  SDEM_ELIG
      EC_PC_YES 
	  EC_ALL_2 RAND_ELE RAND_ARM ;
KEYLABEL COLPCTN='%' ;
TABLE (R_race ALL)*(N /*COLPCTN*/)
,(DEM_RACE_HISP*SDEM_SEX ALL)
;
RUN;




/**********************************************FOR RANDOMIZED ONLY*/
TITLE "FOR RANDOMIZED PTS ONLY";
PROC FREQ DATA=R2_RACECHECK;
TABLES REDCAP_DATA_ACCESS_GROUP*RAND_ARM;
RUN;

PROC TABULATE DATA=R2_RACECHECK(WHERE= (RAND_ARM NE .)) MISSING;
BY REDCAP_DATA_ACCESS_GROUP;
CLASS REDCAP_DATA_ACCESS_GROUP 
      DEM_RACE_HISP
	  R_race
	  SDEM_SEX
	  SDEM_ELIG
      EC_PC_YES 
	  EC_ALL_2 RAND_ELE RAND_ARM ;
KEYLABEL COLPCTN='%' ;
TABLE (R_race ALL)*(N /*COLPCTN*/)
,(DEM_RACE_HISP*SDEM_SEX ALL)
;
RUN;