/*SUSTAINED PREP OUTCOME:*/
/*1.	YOUR DEFINITION BELOW OF 8WKS POST-INITIATION THROUGH 6 MONTHS, AND WE ARE ALSO ADDING 12 MONTHS POST. */
/*LG:  DAN’S FEEDBACK ON OCT 5TH WAS TO USE “ANY DBS IN THE PERIOD.” GIVEN THIS, TO ASSESS AVAILABILITY OF PRIMARY OUTCOME DATA FOR THIS PREP PRIMARY, I BELIEVE THAT ALL RANDOMIZED PTS ARE INCLUDED IN THE DENOMINATOR AND THE DENOMINATOR VALUE FOR EACH PT IS THE # OF EXPECTED DBS (0, 1, 2 OR 3). THE NUMERATOR IS NUMBER OF COLLECTED/RECORDED DBS (0, 1, 2 OR “3 OR MORE”) AND IS BASED ON THE NUMBER OF DBS COLLECTED DURING THE FOLLOWING PERIOD:  8WKS POST-RAND THROUGH 6MO POST-RAND.*/
/*•	IF A PT IS NOT PRESCRIBED PREP W/IN 6MO POST-RAND, THEN HIS “SCORE” WOULD BE 0/0. */
/*•	IF A PT IS PRESCRIBED PREP W/IN 6MO POST-RAND, THEN HIS DENOMINATOR WOULD BE SET AS 1, 2 OR 3 ACCORDING TO WHEN IN THAT 6MO WINDOW HE INITIATED PREP.*/
/*TO DESCRIBE AVAILABILITY OF THIS OUTCOME (AS PART OF OUR “RETENTION” REPORTS), AND BASED ON THE ABOVE, I AM CONSIDERING ALL PTS WITH A SCORE OF 0/0 OR WHO HAVE A NUMERATOR VALUE < DENOMINATOR VALUE (E.G., 0/1, 0/2, 0/3, 1/2, 1/3 OR 2/3) AS A 0 -- OUTCOME DATA NOT AVAILABLE AND ALL PTS WITH A NUMERATOR VALUE =/> DENOMINATOR (E.G., 1/1, 2/2, 3/3, 4/3, 5/3) AS A 1 – OUTCOME DATA AVAILABLE.*/
/**/
/*WHAT I DO NOT KNOW IS THE CUTOFF THAT DAN WANTS TO USE FOR “6MO POST-RAND.” THIS COULD BE MEASURED AT THE 6-MO VISIT “TARGET DATE” (183 DAYS POST-RAND) OR AT THE CLOSE OF THE 6-MO WINDOW (245 DAYS POST-RAND).  */



/********************************************DBS IN BASELINE AND FOLLOW UP */



/*STEP0*/
/*IMPORT DBS EXCEL FILE FROM ONE DRIVE, FIRST NEED TO DOWNLOAD THE FILE*/
/*HTTPS://MIAMIEDU-MY.SHAREPOINT.COM/:X:/R/PERSONAL/BXH421_MIAMI_EDU/_LAYOUTS/15/DOC.ASPX?SOURCEDOC=%7B7508281D-9040-4612-A7FA-003757D34714%7D&ACTION=DEFAULT*/
/* USE SAS IMPORT TO IMPORT THE DATA, NEED TO 

1.CHANGE DATASET NAME TO DBS, AND 
2. CHANGE THE READING FROM A2, 
3. CHANGE FORMAT TO DATE
4. Ask gaby to add color indicator in the log

*/




/*STEP1*/
/*THEN JOIN THE R2_DBS FILE*/



/*CHECK FOR FOLLOW UP*/
PROC SQL;
   CREATE TABLE R2_DBS AS 
   SELECT 
		  T1.RECORD_ID, 
/*          T1.REDCAP_EVENT_NAME, */
          T1.REDCAP_DATA_ACCESS_GROUP, 
		  T1.SDEM_OAT,
/*          T1.SDEM_ELIG, */
          T1.SDEM_VISIT, 
          T1.RAND_DATE, 
/*          T1.EC_PC_YES, */
/*          T1.EC_ALL_2, */
/*          T1.EC_SIGN, */
/*          T1.EC_COMMENTS, */
          T1.RAND_ELE, 
          T1.RAND_ARM, 
/*          T1.RAND_REASON, */
/*          T1.RAND_WHY, */
/*          T1.RAND_OTHER, */

/*ADD DBS_DAS FROM R1_BASE*/
		  T2.DBS_BAS,
		  T3.DBS_BAS_3M AS DBS_BAS_3M,
		  T4.DBS_BAS_3M AS DBS_BAS_6M,

		  T5.F3	AS RAND_DATE_IDEA,
		  T5._1_MONTH AS DBS_LOGDATE_1M,
		  T5.MONTH_2_DBS AS DBS_LOGDATE_2M,	
		  T5.MONTH_3_DBS AS DBS_LOGDATE_3M,		
		  T5.MONTH_4_DBS AS DBS_LOGDATE_4M,		
		  T5.MONTH_5_DBS AS DBS_LOGDATE_5M,		
		  T5.MONTH_6_DBS AS DBS_LOGDATE_6M,



      FROM WORK.R2(WHERE=(RAND_DATE NE .))  T1 LEFT JOIN R1_BASE T2 ON
			   T1.RECORD_ID=T2.RECORD_ID LEFT JOIN R1_3M T3 ON 
			   T1.RECORD_ID=T3.RECORD_ID LEFT JOIN R1_6M T4 ON 
			   T1.RECORD_ID=T4.RECORD_ID LEFT JOIN dbs T5 ON 
			   T1.RECORD_ID=T5.F1
	  ORDER BY T1.REDCAP_DATA_ACCESS_GROUP,
	           T1.RAND_DATE

;
 QUIT;


PROC FREQ DATA=R2_DBS;
TABLE DBS_BAS DBS_BAS_3M DBS_BAS_6M;
RUN;


